### ISSUE TITLE
progressbar issue in example

### ISSUE THREAD

**Issue by inv2004** [kcvinker/Nimforms#2]
OS: win-11
Nim: 1.6.12

After click "Normal" button:

![image](https://user-images.githubusercontent.com/4949069/232252160-a4512e6e-a9d5-4f1b-9384-d61d8be250b2.png)

**Comment by kcvinker** [comment]
@inv2004, Seems like you missed the manifest file. There is a manifest file in this repo. Download it and place it near your exe file. If your exe file's name is `app.exe`, then the manifest file's name must be `app.exe.manifest`. Then compile again and run.

**Comment by inv2004** [comment]
@kcvinker it works, Thank you
