### ISSUE TITLE
Just compiling the sample will cause the following duplicate error. 

### ISSUE THREAD

**Issue by oh-kan** [kcvinker/Nimforms#3]
--- error content ---
contextmenu.nim(6, 5) Error: redefinition of 'TPM_LEFTBUTTON'; previous declaration here: apimodule.nim(182, 5)

To fix this, comment out lines 5-6 of contextmenu.nim.

**Comment by kcvinker** [comment]
Noted. Will be corrected and push the updated version tonight.

**Comment by kcvinker** [comment]
@oh-kan,
Fixed and pushed. Please check.

**Comment by oh-kan** [comment]
Thank you for your quick response.

I am Japanese. I am sorry for my poor English.
