### ISSUE TITLE
When the button is clicked with the mouse, the program crashes.

### ISSUE THREAD

**Issue by oh-kan** [kcvinker/Nimforms#4]
--- My PC environment ---
Windows 11 pro
nim lang 1.6.12

--- error comment ---
lib\pure\collections\tables.nim(234) raiseKeyError
Error: unhandled exception: key not found: 100 [KeyError]

The reason is that the WM_COMMAND event in forms.nim refers to an empty table. 
To fix this, lines 452 of forms.nim.
if len(this.mMenuItemDict) == 0:
    return.

**Comment by kcvinker** [comment]
Thank you for reporting the error. Let me check that.

**Comment by kcvinker** [comment]
@oh-kan,
Fixed and pushed. Please clone and check.

**Comment by oh-kan** [comment]
Thank you for your quick response.
