### ISSUE TITLE
I cannot change the background color of the form.

### ISSUE THREAD

**Issue by oh-kan** [kcvinker/Nimforms#5]
--- My PC environment ---
Windows 11 pro
nim lang 1.6.12
gcc-11.1.0-mingw-w64-8.0.2-r1

--- My program ---
import Nimforms/nimforms

var frm = newForm("Nimforms GUI Library", 860, 600)
frm.font = newFont("メイリオ", 11)  　# Japanese font
frm.foreColor = 0xECE78E
frm.backColor = 0x53A1EE

Can't I change the color of the form?

**Comment by kcvinker** [comment]
Is it ? That's strange. Let me check that.

**Comment by kcvinker** [comment]
@oh-kan,
Fixed and pushed. Please check.

**Comment by oh-kan** [comment]
Thank you for changing the color of the form. However, I have another issue: the gradient color of the button has disappeared.

**Comment by oh-kan** [comment]
I will close this issue for now. I will create a new issue separately.
