### ISSUE TITLE
Sample not filling widgets with proper data

### ISSUE THREAD

**Issue by SpiderDave** [kcvinker/Nimforms#7]
After correcting the import to Nimforms/nimforms, building the sample gives me this result:

![screenshot](https://i.imgur.com/puCgP4U.png)

**Comment by kcvinker** [comment]
Oh, seems like a text rendering problem. Let me check that. BTW, you can try to create a simple window without any controls. I mean without using the sample code, you can create your own Nimforms project and import this library.

**Comment by SpiderDave** [comment]
With this minimal code, the title bar is blank, just like with the demo.

```nim
import Nimforms/nimforms

var frm = newForm("Hello World", 900, 500)
frm.createHandle(true)

frm.display()
```

**Comment by kcvinker** [comment]
So, that is clearly a text rendering issue. Do you have the manifest file in your folder where the nim file resides ?

**Comment by SpiderDave** [comment]
Yes it's the one copied from the instructions, and named correctly.
```
app.exe
app.exe.manifest
```

```
Windows 11 Pro
Nim Compiler Version 2.2.0 [Windows: amd64]
Compiled at 2024-10-02
```

**Comment by kcvinker** [comment]
Okay, now, can you please show me your command to nim compiler ?

**Comment by SpiderDave** [comment]
```
nim c --app:gui --threads:on --opt:size "main.nim"
```

(I rename the .exe afterwards)

Removing --threads:on and --opt:size doesn't make a difference with the issue either.

**Comment by kcvinker** [comment]
@SpiderDave 
Do one thing. rename you `main.nim` to `app.nim` and compile again. That will fix the issue, I think.

**Comment by SpiderDave** [comment]
Still happens.

**Comment by kcvinker** [comment]
So `nim c --app:gui --threads:on --opt:size "app.nim"` creates an exe file named `app.exe` and in the same folder you have the manifest file named `app.exe.manifest`. But still there is no text, right ?

**Comment by kcvinker** [comment]
Anyways, try with this - ` --mm:refc`

**Comment by SpiderDave** [comment]
`--mm:refc` fixed it, works. :)

EDIT: Works with blank project, and demo, and renaming is fine as well.

**Comment by kcvinker** [comment]
Glad to know that. So I am gonna include this info in read me file. And I am closing this issue.
